import '../css/pages/VerificationStatusPage.css';

function VerificationStatusPage({ memberData, onClose }) {
  const formatDisplayValue = (value) => {
    if (value === null || value === undefined || value === '') {
      return 'Not provided';
    }

    if (typeof value === 'string' && value.trim() === '') {
      return 'Not provided';
    }

    return String(value);
  };

  const getStatusTone = () => {
    const normalizedOutcome = String(memberData?.outcome || '').toLowerCase();
    const normalizedStatus = String(memberData?.status || '').toLowerCase();

    if (normalizedOutcome === 'invalid' || normalizedStatus === 'invalid') {
      return 'danger';
    }

    if (normalizedOutcome === 'expired' || normalizedStatus === 'expired') {
      return 'warning';
    }

    if (!memberData?.expiresAt) {
      return 'success';
    }

    const expiryDate = new Date(memberData.expiresAt);
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    if (Number.isNaN(expiryDate.getTime())) {
      return 'success';
    }

    if (expiryDate < today) {
      return 'warning';
    }

    const daysLeft = Math.ceil((expiryDate - today) / (1000 * 60 * 60 * 24));
    if (daysLeft <= 30) {
      return 'warning';
    }

    return 'success';
  };

  const stateTone = getStatusTone();
  const isInvalidState = ['invalid', 'unrecognized', 'not found'].includes(String(memberData?.outcome || '').toLowerCase()) || ['invalid', 'unrecognized', 'not found'].includes(String(memberData?.status || '').toLowerCase());
  const isExpiredState = ['expired'].includes(String(memberData?.outcome || '').toLowerCase()) || ['expired'].includes(String(memberData?.status || '').toLowerCase()) || (memberData?.expiresAt && new Date(memberData.expiresAt) < new Date(new Date().setHours(0, 0, 0, 0)));

  if (!memberData) {
    return (
      <section className="verification-status-page">
        <div className="status-container empty-state">
          <p>No verification data to display.</p>
          <button onClick={onClose} className="close-btn">Close</button>
        </div>
      </section>
    );
  }

  const detailItems = [
    { label: 'Name', value: formatDisplayValue(memberData.name || 'Unrecognized code') },
    { label: 'Status', value: formatDisplayValue(isInvalidState ? 'Invalid' : isExpiredState ? 'Expired' : memberData.status || 'Verified') },
    { label: 'Position', value: formatDisplayValue(memberData.tag || 'Member') },
    { label: 'Membership Number', value: formatDisplayValue(memberData.membershipId) },
  ];

  return (
    <section className="verification-status-page">
      <div className={`status-container ${stateTone}`}>
        <div className="verification-message">
          <div className="success-icon" aria-hidden="true">{isInvalidState || isExpiredState ? '!' : '✓'}</div>
          <h2>
            {isInvalidState ? (
              <>
                <span className="member-name">This QR code</span>
                <span className="is-verified"> could not be verified</span>
              </>
            ) : isExpiredState ? (
              <>
                <span className="member-name">{formatDisplayValue(memberData.name || 'This membership')}</span>
                <span className="is-verified"> has expired</span>
              </>
            ) : (
              <>
                <span className="member-name">{formatDisplayValue(memberData.name)}</span>
                <span className="is-verified"> is a verified member of</span>
                <span className="rhopee-text"> RHOPEE</span>
              </>
            )}
          </h2>
          <p className="status-subtitle">
            {isInvalidState
              ? 'The code is invalid, unrecognized, or was not generated by RHOPEE.'
              : isExpiredState
                ? 'The member’s access has expired and the ID is no longer active.'
                : 'This is to inform you that the holder of this ID is a verified member of RHOPEE.'}
          </p>
          {memberData.reason ? <p className="status-subtitle">{formatDisplayValue(memberData.reason)}</p> : null}
        </div>

        <div className="details-card">
          <div className="detail-grid">
            {detailItems.map((item) => (
              <div className="detail-item" key={item.label}>
                <span className="detail-label">{item.label}</span>
                <span className="detail-value">{item.value}</span>
              </div>
            ))}
          </div>
        </div>

        <div className="action-buttons">
          <button onClick={onClose} className="close-btn">
            Close and return home
          </button>
        </div>
      </div>
    </section>
  );
}

export default VerificationStatusPage;
